version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: shopping_list_nginx
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: shopping_list_php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: 'mysql'
    container_name: shopping_list_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'shopping_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: shopping_list_phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data:
